[package]
name = "Delta"
version = "1.0.0"
authors = []

[addresses]
vault = "0xf2305c21e98fab885a572f252ac43f73a1e3d2d6959cc9ba6d99186b2e952a1d"
[dev-addresses]

[dependencies]
decibel_perp_dex = { local = "./deps/decibel/decibel_perp_dex" }
decibel_accounts = { local = "./deps/decibel/decibel_accounts" }

[dev-dependencies]
